<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'AphrontResponse' => 'aphront/response/AphrontResponse.php',
    'CelerityStaticResourceResponse' => 'applications/celerity/CelerityStaticResourceResponse.php',
    'PhabricatorAuthProvider' => 'applications/auth/provider/PhabricatorAuthProvider.php',
    'PhabricatorAuthStartController' => 'applications/auth/controller/PhabricatorAuthStartController.php',
    'PhabricatorGoogleIAPAuthProvider' => 'applications/auth/provider/PhabricatorGoogleIAPAuthProvider.php',
    'PhabricatorProjectBoardViewController' => 'applications/project/controller/PhabricatorProjectBoardViewController.php',
    'ProjectBoardTaskCard' => 'applications/project/view/ProjectBoardTaskCard.php',
    'UserQueryConduitAPIMethod' => 'applications/people/conduit/UserQueryConduitAPIMethod.php',
  ),
  'function' => array(),
  'xmap' => array(
    'AphrontResponse' => 'Phobject',
    'CelerityStaticResourceResponse' => 'Phobject',
    'PhabricatorAuthProvider' => 'Phobject',
    'PhabricatorAuthStartController' => 'PhabricatorAuthController',
    'PhabricatorGoogleIAPAuthProvider' => 'PhabricatorAuthProvider',
    'PhabricatorProjectBoardViewController' => 'PhabricatorProjectBoardController',
    'ProjectBoardTaskCard' => 'Phobject',
    'UserQueryConduitAPIMethod' => 'UserConduitAPIMethod',
  ),
));
